# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-assets
  
title: "Nipun Chronicles"
email: nipun1deelaka@gmail.com
description: "Innovating with Intelligence: My AI Odyssey."
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: 
cv_url: assets/pdf/cv.pdf
repository: nipdep/portfolio
twitter: NipunDeelaka
github: nipdep

header_image: assets/images/profile_pic3.png

google_analytics:
  tracking_id: G-H2K6ZWCRB5
comments: true
disqus: purelog-jekyll

author: Pathirage N. Deelaka
author_bio: >-
  I am a self-driven recent graduate, deeply immersed in the world of deep learning and data science, equipped with a strong technical foundation. 
  My passion lies in constantly challenging myself, stepping out of my comfort zone, and seizing every opportunity to acquire new knowledge and advancements in the realm of artificial intelligence.
author_pic: https://brennanbrown.ca/img/avatar.png
paginate: 4
paginate_path: "/:num/"

markdown: kramdown

sass:
  style: compressed

assets:
  baseurl: /assets

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
